export const MOCK_CARD_LIST = [
  {
    id: 0,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 1,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 2,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 3,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 4,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 5,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
];

export const MOCK_MENU_LIST = [
  { eng: 'free', kor: '자유 ' },
  { eng: 'advertise', kor: '홍보' },
  { eng: 'club', kor: '동아리' },
  { eng: 'study', kor: '스터디' },
  { eng: 'info', kor: '정보' },
];

export const MOCK_COMMENT_LIST = [
  {
    id: 0,
    content: '댓글 테스트1',
    creator: { uid: 'ASDQWR', nickname: '후니', avatarId: 1 },
    created_at: '2021.10.17',
    like_count: 0,
    liker_list: [],
  },
  {
    id: 1,
    content: '댓글 테스트2',
    creator: { uid: 'ASDQWR', nickname: 'zzz', avatarId: 1 },
    created_at: '2021.10.17',
    like_count: 0,
  },
  {
    id: 2,
    content: '댓글 테스트1',
    creator: { uid: 'ASDQWR', nickname: 'dddddd', avatarId: 3 },
    created_at: '2021.10.17',
    like_count: 0,
  },
  {
    id: 3,
    content: '댓글 테스트1',
    creator: { uid: 'ASDQWR', nickname: '123', avatarId: 5 },
    created_at: '2021.10.17',
    like_count: 0,
  },
  {
    id: 4,
    content: '댓글 테스트1',
    creator: { uid: 'ASDQWR', nickname: 'dasd', avatarId: 8 },
    created_at: '2021.10.17',
    like_count: 0,
  },
];
