export const MOCK_CARD_LIST = [
  {
    id: 0,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 1,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 2,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 3,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 4,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
  {
    id: 5,
    title: '기타 동아리 하실 분',
    content: '통기타 좋아하시는 분~ 주 1회 정도 모여서 같이 연습해요',
    creator: '기타짱',
    reply_count: 5,
    view_count: 120,
    like_count: 12,
  },
];

export const MOCK_MENU_LIST = [
  { eng: 'free', kor: '자유 ' },
  { eng: 'advertise', kor: '홍보' },
  { eng: 'club', kor: '동아리' },
  { eng: 'study', kor: '스터디' },
  { eng: 'info', kor: '정보' },
];
